### ISSUE TITLE
DropDatabaseObjects - System.ArgumentNullException: Value cannot be null.  Parameter name: source 

### ISSUE THREAD

**Issue by norfas** [christiandelbianco/monitor-table-change-with-sqltabledependency#93] opened 2018-09-04 08:49 UTC
I get an occasional error listed below.
I assume it occurs on line #370 in .SqlTableDependency`1.DropDatabaseObjects():
```C#
var dropMessages = string.Join(Environment.NewLine, _processableMessages.Select(pm => string.Format("IF EXISTS (SELECT * FROM sys.service_message_types WITH (NOLOCK) WHERE name = N'{0}') DROP MESSAGE TYPE [{0}];", pm)));
```

Should not it check for _processableMessages being null?

>**System.ArgumentNullException: Value cannot be null.  Parameter name: source**
>at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable\`1 source, Func\`2 selector)    
>at TableDependency.SqlClient.SqlTableDependency\`1.DropDatabaseObjects()    
>at TableDependency.SqlClient.Base.TableDependency\`1.Stop()    
>at TableDependency.SqlClient.Base.TableDependency\`1.Dispose(Boolean disposing)

**Comment by christiandelbianco** [comment] 2018-09-04 11:01
Hi, can you give me more details? I really need a way to reproduce this issue, otherwise it is impossible to fix it. Thanks.

**Comment by norfas** [comment] 2018-09-04 12:27
Unfortunately not yet. I just saw this exception in our log.
I will let you know if I find more about it.
In any case this exception may occur if _processableMessages is null in the line I quoted.

**Comment by norfas** [comment] 2018-09-04 13:05
I checked a bit more.
It looks an exception in DropDatabaseObjects occurs when "Dispose" is called on SqlTableDependency object that failed to "start" properly due to a timeout in DB.

See code below (the code snippet below is just to illustrate the test-case):
```C#
SqlTableDependency<TableDataChangeAbc> tableDependency;
try{
    tableDependency = new SqlTableDependency<TableDataChangeAbc>(s, "tblAbc", "dbo", mapper); 
    tableDependency.Start(); // may time out, and then Dispose is called below
}
catch()
{
    if (tableDependency != null)
        tableDependency.Dispose(); // exception occurs here
}
```
Example of a time out that eventually leads to an exception on Dispose is shown below:
```
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  
The timeout period elapsed prior to completion of the operation or the server is not responding. ---> 
System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out     
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)     
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)     
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)     
at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)     
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)     
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()     
at TableDependency.SqlClient.SqlTableDependency`1.CreateSqlServerDatabaseObjects(IEnumerable`1 userInterestedColumns, String columnsForUpdateOf, Int32 watchDogTimeOut)     
at TableDependency.SqlClient.SqlTableDependency`1.CreateDatabaseObjects(Int32 timeOut, Int32 watchDogTimeOut)     
at TableDependency.SqlClient.Base.TableDependency`1.Start(Int32 timeOut, Int32 watchDogTimeOut)     
at TableDependency.SqlClient.SqlTableDependency`1.Start(Int32 timeOut, Int32 watchDogTimeOut) 
```

**Comment by christiandelbianco** [comment] 2018-09-06 06:35
"_exception in DropDatabaseObjects occurs when "Dispose" is called on SqlTableDependency object that failed to "start" properly due to a timeout in DB_." 

GOOD Analysis. Thanks!!!!!!!!!!!

**Comment by christiandelbianco** [comment] 2018-09-06 07:47
Fixed in source code and in NuGet package version 8.5.2

**Closed by christiandelbianco** 2018-09-06 07:47 UTC
Labels: bug

**Comment by norfas** [comment] 2018-10-22 11:01
Christian, 
Any plans to release v. 8.5.2 in Nuget, I wonder?
I am not familiar with your Nuget release process, and not sure if there is any "roadmap" for releases...

**Comment by christiandelbianco** [comment] 2018-12-08 16:58
Release  v. 8.5.2 in Nuget available starting from Moday 10 December 2018.
Regards.
