### ISSUE TITLE
Stuck table trigger stopping Insert Update or Delete actions

### ISSUE THREAD

**Issue by dakiller** [christiandelbianco/monitor-table-change-with-sqltabledependency#155] opened 2019-09-25 03:56 UTC
Hi,

I'm having intermittent problems where users are getting blocked from Inserts Updates or Deletes on a table in the database.

The error given is -

System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The conversation handle "244D723E-F36B-1410-817E-00D147BD9CA7" is not found.
An error was raised during trigger execution. The batch has been aborted and the user transaction, if any, has been rolled back.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---

Mu current 'fix' is to delete all the triggers that SQLTableDependency has put on the offending table.

I'm using EF6 for my db interactions.

Thanks.

**Comment by christiandelbianco** [comment] 2019-09-25 05:37
Hi
Because i do not have your code, i only can guess what is happening.
For some reason, the db connection used by SqlTableDependency is lost OR SqlTableDependency is not close (using Dispose) correctly. 

I need some more info from you: can you tell me if you see any other database objects (trigger, stored procedure, queue) created by SqlTableDependency? Look for these object searching naming SIMILAR to "dbo_**YOUR TABLE NAME**_23191631-248f-4fcd-ab1e-6c222182d9de" ? Can you tell me if there is a trigger attached to your table but NOT stored procedure with similar name?

**Comment by dakiller** [comment] 2019-09-25 22:36
The clients being WPF applications, I cannot guarantee that the SqlTableDependency gets closed properly via Dispose.

I will look for missing stored procedures next time this issue comes up.

**Comment by christiandelbianco** [comment] 2019-09-26 07:27
Cannot you intercept when the WPF view or application is close? When that happen, you can dispose SqlTableDEpendency.

**Comment by christiandelbianco** [comment] 2019-09-27 17:10
The will will be released with version 8.5.5

**Comment by christiandelbianco** [comment] 2019-09-27 17:49
Fix 8.5.5 details:
SqlTableDepenndency's trigger will check if the conversation handler is still present. If not, trigger will delete its self, preventing your problem.

**Comment by doaji** [comment] 2019-10-14 04:32
Hi, i am having same issues - is this fix available now? also is there a script i can call to manually trigger the delete process of all the generated scripts?

Thanks

**Comment by christiandelbianco** [comment] 2019-10-27 20:00
@dakiller I kindly want to ask you if you can test the fix. I can send you the new nuget package and you can install. Unfortuanatelly i cannot reproduce this error. This is the reason why i am askin you if you can test for me.

**Comment by dakiller** [comment] 2019-10-28 21:11
@christiandelbianco I would gladly test the fix, though with it not being a readily repeatable issue, I can only give it time and see if it pops up again.

**Comment by christiandelbianco** [comment] 2019-11-02 15:33
I have pushed version 8.5.5.
You can download the source code and temporary add SqlTableDependecy in your solution.
Please let me know if this fix resolve your problem: in positive case, i will release nuget package.

**Comment by doaji** [comment] 2019-11-05 13:59
thanks christian. i extended the SqlTableDependency class and added the option to drop all existing sps before creating new ones.. fixed my issue.

**Closed** 2019-11-07 19:34 UTC
Labels: bug

**Comment by rajeshb0205** [comment] 2020-06-30 11:04
hi christian,
if in case there was not any proper dispose of object then after some time if we restart our service then we  want first clear the existing service broker objects and then create new one.
please let me know on this.

**Comment by christiandelbianco** [comment] 2020-06-30 11:07
SqlTableDependency's database object are dropped automatically after 3 minutes (in case there was not any proper dispose).
If yow wanto to drop before, you must do manually

**Comment by rajeshb0205** [comment] 2020-07-02 13:44
> SqlTableDependency's database object are dropped automatically after 3 minutes (in case there was not any proper dispose).
> If yow wanto to drop before, you must do manually


if we want to manually then these below sys  tables are enough, 

SELECT * FROM sys.services
select * from sys.service_queues
select * from sys.service_contracts
select * FROM sys.service_message_types 
select * from sys.objects
select * from sys.conversation_endpoints 

or we need to take any other sys tables then please let me know...
as i am new to this service broker application.
