### ISSUE TITLE
The conversation handle "7F3FE62D-7E62-E811-912A-A4BF011A4992" is not found. An error was raised during trigger execution. The batch has been aborted and the user transaction, if any, has been rolled back

### ISSUE THREAD

**Issue by wzuqui** [christiandelbianco/monitor-table-change-with-sqltabledependency#72] opened 2018-05-28 14:59 UTC
The database trigger was created but the conversation was not.

The triggered events didn't throw any error, but when I try to execute an INSERT statement in the database, the error in the title is thrown.

The message types were not created either.

As you can see in the following screenshot, the message type it's trying to use does not exist in the database.

![image](https://user-images.githubusercontent.com/25418652/40620210-5d52b2f6-626e-11e8-8f88-e5fe9c829ebe.png)

**Comment by christiandelbianco** [comment] 2018-05-28 15:14
Can you send me the SQL script to create your table, as well as the INSERT statement causing the your issue?

**Comment by wzuqui** [comment] 2018-05-28 15:37
USE [RavexV3_Nucleo_Producao]
GO

INSERT INTO [dbo].[Equipamento]
           ([CriadoDatahora]
           ,[ModificadoDatahora]
           ,[Excluido]
           ,[CriadoPor]
           ,[IdEquipamentoTipo]
           ,[NumeroSerial]
           ,[IdVeiculoAtual])
     VALUES
           (<CriadoDatahora, datetime,>
           ,<ModificadoDatahora, datetime,>
           ,<Excluido, bit,>
           ,<CriadoPor, int,>
           ,<IdEquipamentoTipo, int,>
           ,<NumeroSerial, varchar(16),>
           ,<IdVeiculoAtual, int,>)
GO


INSERT INTO [dbo].[Equipamento]
			  (
			   [CriadoDatahora]
			  ,[CriadoPor]
			  ,[Excluido]
			  ,IdEquipamentoTipo
			  ,NumeroSerial
		  ) VALUES
			  (
			   GETUTCDATE()
			  ,@CriadoPor
			  ,@Excluido
			  ,@IdEquipamentoTipo
			  ,@NumeroSerial
		 );
SELECT SCOPE_IDENTITY()

**Comment by christiandelbianco** [comment] 2018-05-29 08:09
I tested using your SQL scripts and it works with no problem as you can see from [video uploaded here](https://ufile.io/xq9fq).

**Comment by dungahk** [comment] 2018-05-29 11:43
Hi, I work with @wzuqui , 

The problem is that this issue doesn't happen every time, I'm not really sure if there's some kind of specific scenario that leads to it, but it happens from time to time.

If I get any further information that could help in finding the issue, I or @wzuqui will share it here, for now, that's all we got.

**Comment by christiandelbianco** [comment] 2018-05-29 12:00
If this "...happens from time to time", I guess that is due to DEBUG or a long task associated to your ONCHANGE EVENT HANDLER. If some activity takes more the 3 minuted to complete, the SQL Server watch dog will dispose every SqlTableDependency object, resulting the error "The conversation handle XXX is not found."

Can you please test simply adding a Thread.Slepp (1000 * 60 * 5) in the OnChange event handler ?

**Comment by christiandelbianco** [comment] 2018-05-30 13:16
It should be fixed.

However, C# model property mapping FLOAT table column, must be a decimal:

![2018-05-30 at 15-13-37](https://user-images.githubusercontent.com/13263017/40722233-10d33ca2-641c-11e8-9732-5c5f897fdd94.png)

This is the table:

![2018-05-30 at 15-11-30](https://user-images.githubusercontent.com/13263017/40722242-16a032ac-641c-11e8-9419-f75bbd64d52d.png)

![2018-05-30 at 15-11-59](https://user-images.githubusercontent.com/13263017/40722249-19c230e8-641c-11e8-9eed-68456eaff640.png)

And this is the result I get now:

![2018-05-30 at 15-14-44](https://user-images.githubusercontent.com/13263017/40722298-37a50d42-641c-11e8-984f-0a58d8809114.png)

Fix available with version **7.4.0**.

**Closed by christiandelbianco** 2018-05-30 13:16 UTC

**Comment by christiandelbianco** [comment] 2018-05-30 13:38
Please have a look at [Remark]() section

**Comment by dungahk** [comment] 2018-05-30 20:26
@christiandelbianco The link is broken

**Comment by dungahk** [comment] 2018-05-30 20:32
First of all, thanks for the package and assisting us in this issue.

Second, we couldn't reproduce the issue using Thread.Sleep(1000 * 60 * 5).

Third, we may have found a reason why this is happening, we got 2 applications in our scenario using your package in the same database and tables, what happens is that when one of our applications restarts, instead of 2 triggers, we end up with 3 triggers.

Sounds like somehow the old trigger is not being removed.

Do you have any thoughts on this? Is this related to the issue?

**Comment by christiandelbianco** [comment] 2018-05-31 08:38
Another question. in addition to this third trigger, can you see also third Queue, Service Broker?

**Comment by christiandelbianco** [comment] 2018-05-31 17:21
Hi, today i created i windows service hosted on my Windows virtual machine. This windows service uses SqlTableDependency. I left this service working for 5 hours and my PC also goes in sleep mode. However, Windows service using SqlTalbeDependency works without any issue: it receives notification on record table change.

**Comment by christiandelbianco** [comment] 2018-06-08 06:52
THANKS!
Can you check if other SqlTableDependency's database object are not deleted too?
For example, there should be two queue with name that is similar to Trigger name but ending with "_sender" and "_receiver".

**Comment by dungahk** [comment] 2018-06-08 12:13
Yes, they didn't get deleted either.

**Comment by christiandelbianco** [comment] 2018-06-08 18:57
Thanks.

Last question: these DB object are still present after 3 minutes since you stop your web application?

**Comment by dungahk** [comment] 2018-06-08 19:07
Yes, they do, we tried waiting for about 10 minutes, and they were still there.

**Comment by christiandelbianco** [comment] 2018-06-09 09:43
I really do not know what to say you. Please have a look to my videos [https://ufile.io/ribbk](https://ufile.io/ribbk) where i have a MVC WebAPI application. As you can see, stopping the Visual Studio debugger, after 3 minutes, trigger is automatically removed from the table.

**Comment by christiandelbianco** [comment] 2018-06-11 08:11
Another Question. Fail trigger deletion happened EVERY TIME or from time to time?
In the first case, may be, your user SQL has no enough grants

**Comment by christiandelbianco** [comment] 2018-06-13 05:32
Can you check Accessing SQL Server Using Windows Integrated Security?

**Comment by dungahk** [comment] 2018-06-15 20:29
We updated the package to the latest version and changed some code, now it works like a charm.

We can't reproduce the issue anymore, you can close it now.

Thanks for the support.

**Comment by Misiu** [comment] 2019-04-26 13:45
@christiandelbianco sorry for returning to an old issue, but I have the exact same problem.
I'm using version 8.5.3 and I'm trying to integrate Your awesome package into ASP.NET Core 2.2 application.
Everything works great until I stop debugging my app (I run app via F5 from VS).
After some time I'm unable to do an update on my table because I get this error:

> Msg 50000, Level 16, State 4, Procedure tr_dbo_PIV_Wniosek_1f546e17-6db4-4b8b-9152-09feb4c8e5b5_Sender, Line 202 [Batch Start Line 0]
> The conversation handle "8FDDD6BA-1168-E911-80F2-00155D009A84" is not found.
> Msg 3616, Level 16, State 1, Line 7
> An error was raised during trigger execution. The batch has been aborted and the user transaction, if any, has been rolled back.

I must manually remove the trigger to be able to update my table. I've examined the trigger, everything is in try/catch, but there is `RAISERROR`, is there an option to generate trigger without that? I can't imagine having that error on the production system.

I've also noticed that every time I stop debugging (Shift + F5) message types, contracts, queues, and services don't get removed.
From what I understand DB objects should get removed after some time (3 minutes). The cleanup is done by DB? How can I validate that this mechanism works?

Must I remove all unneeded DB objects by hand in case my app crashes or I stop debugger/terminate process and I don't call `Stop`?

**Comment by christiandelbianco** [comment] 2019-04-30 07:00
@Misiu The fact SqlTableDependency database object (that are Service Broker, trigger, queue ect...) are still in DB after 3 minutes is very strange. I have a lot of tests checking that after 3 minutes these object are dropped. 

For example: [https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/blob/master/TableDependency.SqlClient.Test/DatabaseObjectAutoCleanUpAfter2InsertsTest.cs](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/blob/master/TableDependency.SqlClient.Test/DatabaseObjectAutoCleanUpAfter2InsertsTest.cs)

In this test, i check with the methods:

```
Assert.IsTrue(base.AreAllDbObjectDisposed(dbObjectsNaming));
Assert.IsTrue(base.CountConversationEndpoints(dbObjectsNaming) == 0);
```

evaluate that SqlTableDependency's objects are removed from DB.

Can you execute this test and check if SqlTableDependency's objects are still in DB?

**Comment by mev9669** [comment] 2019-06-10 09:53
@christiandelbianco , Did you try running multiple MVC applications with signalr sql server backplane? I have a MVC Web project and API project hosted on 2 servers for load balancing and the SqlTableDependency is used with signal r only in web project to provide real time updates from the DB and I get this issue. All the triggers, SP, Messages, Contracts, Services etc are not deleted and stops pushing the updates to the UI. i am using the latest version SQLTableDependency 8.5.3. Any help will be appreciated. Thanks

**Comment by toregua** [comment] 2019-06-18 09:49
Same for me when since i using SqlTableDependecy 8.5.3.0 i have randomly an error : 

The conversation handle "9779B522-A491-E911-B065-0CC47A9A767B" is not found.

Do you have any solutions to unlock my situation because now each time it is using SqlTableDependency it throw this error... ?

I have already tested : Alter database MyDBName set trustworthy on but it changes nothing.
I also try to reinit my broker like this: 
Use master
GO
ALTER DATABASE MyDBName SET NEW_BROKER with rollback immediate;
GO
ALTER DATABASE MyDBName SET ENABLE_BROKER
GO

Not working too.
Please help us

**Comment by vamshikpd** [comment] 2019-07-16 16:45
I got a same problem while using SqlTableDependency. I am not able to update the data in table. here is the error I am getting. Could you please help me

Msg 50000, Level 16, State 4, Procedure tr_dbo_WorkflowObject_c4aef18b-8d8c-4ca6-be61-dcf40b5e73e8_Sender, Line 347 [Batch Start Line 14]
The conversation handle "3D164326-47A7-E911-90F5-005056B02440" is not found.
Msg 3616, Level 16, State 1, Line 16
An error was raised during trigger execution. The batch has been aborted and the user transaction, if any, has been rolled back.

**Comment by dtest7676** [comment] 2019-07-19 10:47
Hi,

I work on an ASP.NET MVC 5 application and use SqlTableDependency 8.5.4 with SignalR 2.4.1.
After some time, i get the same error : 

> Msg 50000, Level 16, State 4, Procedure tr_dbo_<name>_Sender, Line 176 [Batch Start Line 0]
> The conversation handle "<Id>" is not found.
> Msg 3616, Level 16, State 1, Line 23
> An error was raised during trigger execution. The batch has been aborted and the user transaction, if any, has been rolled back.
>

One other thing, some time i have many triggers and stored procedures in database. They are not dropped.

Do you have any suggestion ?

Some ideas : 
- In trigger, add some checks to avoid errors and rollbacks
- Change IIS app pool elapsed time recycle
- In code behind, check if database objects exist and recreate them if necessary

Thanks for your work and your help.

**Comment by virenderkverma** [comment] 2019-08-24 09:56
Faced the same problem, When I checked found two triggers on one table. Which I am tracking.

When I deleted SQL broker trigger and again started broker services this worked fine.

**Comment by wzuqui** [comment] 2019-09-01 04:08
maybe i can help,
Our team  uses an inheritance of SqlTableDependency and an override of the GetBaseObjectsNamingConvention method, and that didn't solve all the problems, but it helps us find which service is unstable. With triggers on zabbix we eventually fixed the tables and restarted the service. For the time being it is serving very well for the 7 running services.

**Comment by Suresh9sb** [comment] 2020-04-15 14:48
Hi christian, 

I know this is very old thread, but I see same problem mentioned above and I not sure folk who rectified issue may be provided solution or approach so that it will be useful for others. 

I am using MVC 5, EF, SQL Server 2016, SignalR ASP.NET, SQLTableDependency. 

SqlTableDependency is in WindowsService and I have made code not to go to ideal state as suggested. 

Windows Service will be restarted every day at night time in production and I see very occasionally
issue is getting 
ERROR TableDependency_Error : server SQLP5AGL02, Sender : dbo_DeptDetails_1a3df6fa-1a3b-4847-adb7-a4b86ca9ff3a, Msg : Invalid object name 'dbo.dbo_DeptDetails_1a3df6fa-1a3b-4847-adb7-a4b86ca9ff3a_Receiver'., InnerEx : 

Windows Service is stopping and not able to realise it is getting stopped

**Comment by Suresh9sb** [comment] 2020-04-15 14:50
> We updated the package to the latest version and changed some code, now it works like a charm.
> 
> We can't reproduce the issue anymore, you can close it now.
> 
> Thanks for the support.

which Version you have moved and what is the steps you have taken to resolve this issue?

**Comment by tomasfabian** [comment] 2020-04-17 13:52
> Hi christian,
> 
> I know this is very old thread, but I see same problem mentioned above and I not sure folk who rectified issue may be provided solution or approach so that it will be useful for others.
> 
> I am using MVC 5, EF, SQL Server 2016, SignalR ASP.NET, SQLTableDependency.
> 
> SqlTableDependency is in WindowsService and I have made code not to go to ideal state as suggested.
> 
> Windows Service will be restarted every day at night time in production and I see very occasionally
> issue is getting
> ERROR TableDependency_Error : server SQLP5AGL02, Sender : dbo_DeptDetails_1a3df6fa-1a3b-4847-adb7-a4b86ca9ff3a, Msg : Invalid object name 'dbo.dbo_DeptDetails_1a3df6fa-1a3b-4847-adb7-a4b86ca9ff3a_Receiver'., InnerEx :
> 
> Windows Service is stopping and not able to realise it is getting stopped

Hi everyone,
lets solve this finally. The problem with not dropped database objects was probably already fixed. I found out in the past that the watch dog wasn't created in the same database transaction, and Christian made some other changes too. I'm using a slightly modified version which tries to reconnect to the same conversation handle. Since then I didn't find any orphaned SqlTableDependency database objects in our environment. 

Be aware that in the latest version a bug was introduced inside the trigger, which can block your table.

I found recently the above mentioned Invalid object name exception only in my development environment. It can be reproduced by putting and hitting a breakpoint somewhere in your code, to stop the execution longer then the timeout period defined in Start. After that period you can Continue the execution of your service and the exception will be thrown, because the watchdog has already dropped all the database objects, due to no response from the client I suppose.
@Suresh9sb What do you mean by:
Windows Service is stopping and not able to realise it is getting stopped

In my opinion its not necessary to restart your Windows service every day.

Is it possible that something blocks your code for longer period then 180s?

Regards, Tomas
