### ISSUE TITLE
The conversation handle "A705917C-4762-E711-9447-000C29C3FCF0" is not found

### ISSUE THREAD

**Issue by dharmesh-parekh** [christiandelbianco/monitor-table-change-with-sqltabledependency#3] opened 2017-07-07 05:00 UTC
I have started SQL table dependency in a table. I gave all the permission to database listed in your document. After some times ,may be in idle condition it is giving status as "Waiting for notification" .

 When I change in table (inserting new record), status is not changing (From waiting for notification) and gives error as "The conversation handle "A705917C-4762-E711-9447-000C29C3FCF0" is not found."

Can you please help me to fix this issue?

**Comment by christiandelbianco** [comment] 2017-07-07 06:01
Hi
Can you send me a zip file containing your solution?
Otherwise is impossible for me to figure out what is the problem.

**Comment by dharmesh-parekh** [comment] 2017-07-07 06:23
I have implemented SQL Table Dependency in a large application and it is confidential. So I cannot share code with you.

I have attached
[stacktrace.txt](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/files/1130165/stacktrace.txt)
 a text file for stack trace of exception. Can you please check it. 

I can also explain scenario in which I am getting this error as...

I implemented SQL table dependency in a windows service. When I start windows service I started SQL table dependency as per your example without setting timeout and watchdog timeout. On end of the day, I closed my system without stop of windows service. On next day, I started my system and windows service automatically started and it will start SQL table dependency. After some times, I am trying to change table records, but status of SQL table dependency shows always as "Waiting for notification" and getting error as "The conversation handle "A705917C-4762-E711-9447-000C29C3FCF0" is not found.".

I want to know below things...
1) When can I get status as  "Waiting for notification"?
2) I have windows service which will run continuously on server. Do I need to set timeout and watchdog timeout?
3) Why I am getting errors given as above?

Awaiting Response

Thanks.

**Comment by christiandelbianco** [comment] 2017-07-07 11:27
Hi....May be I understand. But i need your confirmation.
When you say: "I close my system" you mean shout down your PC ?

**Comment by dharmesh-parekh** [comment] 2017-07-07 11:34
yes, I mean shut down.

**Comment by christiandelbianco** [comment] 2017-07-07 12:09
If you shouth down your computer, service is stopped too.
Because noone is monitoring anymore events table, the SqlTableDependency database objects are DELETEd from DB.

Foy your test, you should install the service in a SERVER.

Every time SqlTableDependency is disposed all database objects used to monitor table changes are disposed too.

**Comment by dharmesh-parekh** [comment] 2017-07-07 12:12
Please read carefully scenario. 

I had written..
"On next day, I started my system and windows service automatically started and it will start SQL table dependency."

So SQL Table dependency will start when system start again.

**Comment by christiandelbianco** [comment] 2017-07-11 07:03
Ok...got it.
I need to reproduce your enviroment. So, at least, can you send me the Windows service code that starts SqlTableDependency, the code that stop it and the code that receive notifications?

**Comment by dharmesh-parekh** [comment] 2017-07-11 08:31
As I told you, I am not able to send you as it is confidential.  I had added code same as your documentation. 

Please Just let me know your answer on below queries..

1.  When can I get status as "Waiting for notification"?
2.  Do I need to set timeout and watchdog timeout?
3.  Can I add table dependency only for insert operations. I do not want to monitor on update/delete operations. 

Thanks.

**Comment by christiandelbianco** [comment] 2017-07-12 12:42
Hi, I guess that your Windows Service in not really shutdown but it is more in a state  between hybrid and hibernate. If ithis is the case, it is normal to receive the error:

"The conversation handle "A705917C-4762-E711-9447-000C29C3FCF0" is not found.".

The conversation handler on DB is disposed after a while. Regardig your question:

1. https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Status-change
2. NO, hust is you debug the change event and this takes more that 3 minutes
3. https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/wiki/Use-case:-Filter-notification-by-operation-type

**Comment by christiandelbianco** [comment] 2017-07-17 15:43
As i did not receive any feedback, I will close this bug.
Regards

**Closed by christiandelbianco** 2017-07-17 15:43 UTC
